modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://legacy.curseforge.com/minecraft/mc-mods/exo-craft/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
itemIcon="exocraft:legion_helmet"
updateJSONURL="https://raw.githubusercontent.com/XxRexRaptorxX/Update-Checker/main/ExoCraft.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/exo-craft"
logoFile="logo.png"
#credits=""
authors="${mod_authors}"
description='''This Titanfall / Anthem inspired mod adds exosuits with different cool effects to the game!'''


[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${mc_version_range}"
ordering="NONE"
side="BOTH"

