modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://legacy.curseforge.com/minecraft/mc-mods/exo-craft/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
itemIcon="exocraft:legion_helmet"
updateJSONURL="https://raw.githubusercontent.com/XxRexRaptorxX/Update-Checker/main/ExoCraft_NEO.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/exo-craft"
logoFile="logo.png"
#credits=""
authors="${mod_authors}"
description='''This Titanfall / Anthem inspired mod adds exosuits with different cool effects to the game!'''

[[mixins]]
config="${mod_id}.mixins.json"


[[dependencies.${mod_id}]]
modId="neoforge"
mandatory=true
type="required"
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
type="required"
versionRange="${mc_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="energizedpower"
mandatory=false
type="optional"
reason="Makes it possible to produce your own units with the new machines."
versionRange="1.20.0"
ordering="NONE"
side="BOTH"
