modLoader="javafml"
loaderVersion="41"
license="All rights reserved"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/exo-craft/issues"

[[mods]]
modId="exocraft"
version="2.3.1"
displayName="EXO-Craft"
itemIcon="exocraft:legion_helmet"
updateJSONURL="https://raw.githubusercontent.com/XxRexRaptorxX/Update-Checker/main/ExoCraft.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/exo-craft"
logoFile="logo.png"
#credits=""
authors="XxRexRaptorxX"
description='''This Titanfall / Anthem inspired mod adds exosuits with different cool effects to the game!'''


[[dependencies.exocraft]]
modId="forge"
mandatory=true
versionRange="[41.0.98,)"
ordering="NONE"
side="BOTH"

[[dependencies.exocraft]]
modId="minecraft"
mandatory=true
versionRange="[1.19,1.19.3)"
ordering="NONE"
side="BOTH"

